test('This should pass', () => {

})

test('This should fail', () => {
    throw new Error('Failure!')
})